### ISSUE TITLE
Doesn't work on runkit.

### ISSUE THREAD

**Issue by saisankargochhayat** [WhoopInc/interpo#1]
Also does it support extrapolation ?

**Comment by benesch** [comment]
Thanks for the report, @saisankargochhayat! I assume interpo doesn't work on RunKit because this package hasn't been tested with anything but Node v0.10—ancient, I know. I just released v1.0.1, which should be compatible with everything between v0.10 and the latest released version of node. Not sure how long it takes RunKit to pick up new versions, but give it a whirl in a bit and see if it works!

No support for interpolation, I'm afraid. Pull requests welcome, though I think you'll find the Fortran code that backs this library rather, er, difficult to work with.

**Comment by saisankargochhayat** [comment]
Thanks for the prompt reply , I m really bad with mathematical functions though will give it a try.
